language: node_js
jobs:
  include:
    - stage: test
      node_js: 'node'
      script: yarn test:coverage
      after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
    - stage: build
      node_js: 'node'
      script:
        - |
          yarn && \
          yarn build && \
          yarn docs
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: docs
        on:
          branch: master
