language: node_js
node_js:
- '6'
- '7'
- 'node'
jobs
  include:
    - stage: build
      node_js: 'node'
      script: yarn build
      script: yarn docs
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: docs
        on:
          branch: master
